### PR TITLE
Topplings bugs fixed

### PR DESCRIPTION
**Pull request by falconis**
Thanks for contributing. Your contribution might help someone understand the concepts better.

However, to make sure things are working properly, here's a checklist. Just make sure you check them.
- [x] I am reading these checkboxes. 
- [x] Read [contribution guidelines](CONTRIBUTING.md)
- [x] Link to the [demo](https://falconis.github.io/cool-physics/toppling/).

Here are some optional checkboxes. You can leave them unchecked if you want to.
- [ ] Added some help text to understand the concept. Markdown/HTML would work.

### CODE REVIEW

**Comment by himanshub16** [comment]
Awesome @falconis .
 Loved it.
I'm merging it for now. However, would request you to fix the issue described by the attached clip.
image

**Comment by falconis** [comment]
Ohh, it's still happening. I took care to resolve it. I'll work on it as soon as possible!

**Comment by falconis** [comment]
I would also like to work on another concept. Where can I discuss about that?

**Comment by himanshub16** [comment]
Propose one in issues. Then we can discuss. Read CONTRIBUTING.md

**Comment by himanshub16** [comment]
Fixes #2

**Pull request merged**
