### PR TITLE
Added graphs for escape velocity

### PR DESCRIPTION
**Pull request by Mysterious19**
Thanks for contributing. Your contribution might help someone understand the concepts better.

However, to make sure things are working properly, here's a checklist. Just make sure you check them.
- [x] I am reading these checkboxes. 
- [x] Read [contribution guidelines](CONTRIBUTING.md)
- [x] Link to the [demo](https://mysterious19.github.io/cool-physics/escape-velocity-graphs/).

Here are some optional checkboxes. You can leave them unchecked if you want to.
- [ ] Added some help text to understand the concept. Markdown/HTML would work.

### CODE REVIEW

**Comment by himanshub16** [comment]
Awesome. 💯 

However, there are few points to care about:
- [ ] The code is for `free-fall` and resides in `escape-velocity` directory. Please fix that.
- [ ] Since there is very less space required for graph sliders, you can just lay them out next to each other.
- [ ] Provide some hint to scroll down to see charts.

**Comment by Mysterious19** [comment]
@himanshub16 sir please review the changes.
Link to review - 
https://mysterious19.github.io/cool-physics/free-fall-graphs/

**Comment by himanshub16** [comment]
* Mark the check-boxes. This helps to understand what has been done.
* No *sir/madam* in community conversations.

**Comment by himanshub16** [comment]
Fixes #4

**Pull request merged**
